In [1]:
import pandas as pd

In [56]:
df=pd.read_csv('Superstore_Sales.csv', encoding='latin-1')
# encoding='utf-8' by default we change latin-1 bcz my data contains \,- kind of symbals

In [57]:
# 1.Viewing Dataset
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [58]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [59]:
df.shape

(9994, 21)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [61]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [62]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [63]:
# |Data Cleaning

# Handing Missing Values
df.isna().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [64]:
# Handing Duplicate Values
df.duplicated().sum()

np.int64(0)

In [65]:
# Handing Date Columns 
print('Before :')
print('Data Type of Order Date : ',df['Order Date'].dtypes)
print('Data Type of Ship Date : ',df['Ship Date'].dtypes)
print('After :')
df['Order Date']=pd.to_datetime(df['Order Date'])
df['Ship Date']=pd.to_datetime(df['Ship Date'])
print('Data Type of Order Date : ',df['Order Date'].dtypes)
print('Data Type of Ship Date : ',df['Ship Date'].dtypes)

Before :
Data Type of Order Date :  object
Data Type of Ship Date :  object
After :
Data Type of Order Date :  datetime64[ns]
Data Type of Ship Date :  datetime64[ns]

In [69]:
# Handling Categorical Columns
# Ship Mode,Segment,Country,Region,Category,Sub-Category
print('Values in Ship Mode : ',df['Ship Mode'].unique())
print('Data Type of Ship Mode : ',df['Ship Mode'].unique().dtype)
print('\n')
print('Values in Segment : ',df['Segment'].unique())
print('Data Type of Segment : ',df['Segment'].unique().dtype)
print('\n')
print('Values in Country : ',df['Country'].unique())
print('Data Type of Country : ',df['Country'].unique().dtype)
print('\n')
print('Values in Region : ',df['Region'].unique())
print('Data Type of Region : ',df['Region'].unique().dtype)
print('\n')
print('Values in Category : ',df['Category'].unique())
print('Data Type of Category : ',df['Category'].unique().dtype)
print('\n')
print('Values in Sub-Category : ',df['Sub-Category'].unique())
print('Data Type of Sub-Category : ',df['Sub-Category'].unique().dtype)

Values in Ship Mode :  ['Second Class' 'Standard Class' 'First Class' 'Same Day']
Data Type of Ship Mode :  object


Values in Segment :  ['Consumer' 'Corporate' 'Home Office']
Data Type of Segment :  object


Values in Country :  ['United States']
Data Type of Country :  object


Values in Region :  ['South' 'West' 'Central' 'East']
Data Type of Region :  object


Values in Category :  ['Furniture' 'Office Supplies' 'Technology']
Data Type of Category :  object


Values in Sub-Category :  ['Bookcases' 'Chairs' 'Labels' 'Tables' 'Storage' 'Furnishings' 'Art'
 'Phones' 'Binders' 'Appliances' 'Paper' 'Accessories' 'Envelopes'
 'Fasteners' 'Supplies' 'Machines' 'Copiers']
Data Type of Sub-Category :  object

In [71]:
# Ship Mode,Segment,Country,Region,Category,Sub-Category
df['Ship Mode']=df['Ship Mode'].astype('category')
df['Segment']=df['Segment'].astype('category')
df['Country']=df['Country'].astype('category')
df['Region']=df['Region'].astype('category')
df['Category']=df['Category'].astype('category')
df['Sub-Category']=df['Sub-Category'].astype('category')

In [72]:
print('Values in Ship Mode : ',df['Ship Mode'].unique())
print('Data Type of Ship Mode : ',df['Ship Mode'].unique().dtype)
print('\n')
print('Values in Segment : ',df['Segment'].unique())
print('Data Type of Segment : ',df['Segment'].unique().dtype)
print('\n')
print('Values in Country : ',df['Country'].unique())
print('Data Type of Country : ',df['Country'].unique().dtype)
print('\n')
print('Values in Region : ',df['Region'].unique())
print('Data Type of Region : ',df['Region'].unique().dtype)
print('\n')
print('Values in Category : ',df['Category'].unique())
print('Data Type of Category : ',df['Category'].unique().dtype)
print('\n')
print('Values in Sub-Category : ',df['Sub-Category'].unique())
print('Data Type of Sub-Category : ',df['Sub-Category'].unique().dtype)

Values in Ship Mode :  ['Second Class', 'Standard Class', 'First Class', 'Same Day']
Categories (4, object): ['First Class', 'Same Day', 'Second Class', 'Standard Class']
Data Type of Ship Mode :  category


Values in Segment :  ['Consumer', 'Corporate', 'Home Office']
Categories (3, object): ['Consumer', 'Corporate', 'Home Office']
Data Type of Segment :  category


Values in Country :  ['United States']
Categories (1, object): ['United States']
Data Type of Country :  category


Values in Region :  ['South', 'West', 'Central', 'East']
Categories (4, object): ['Central', 'East', 'South', 'West']
Data Type of Region :  category


Values in Category :  ['Furniture', 'Office Supplies', 'Technology']
Categories (3, object): ['Furniture', 'Office Supplies', 'Technology']
Data Type of Category :  category


Values in Sub-Category :  ['Bookcases', 'Chairs', 'Labels', 'Tables', 'Storage', ..., 'Envelopes', 'Fasteners', 'Supplies', 'Machines', 'Copiers']
Length: 17
Categories (17, object): ['Accessories', 'Appliances', 'Art', 'Binders', ..., 'Phones', 'Storage', 'Supplies', 'Tables']
Data Type of Sub-Category :  category

In [73]:
# Now we have checked that there is no duplicate nor missing values in our data 
# We also handle categorical data

In [ ]:
# Cheking Data Inconsistency : Whitespace issues or Inconsistent spelling
print(df['Category'].value_counts())
print('\n')
print(df['Region'].value_counts())
print('\n')
print(df['Sub-Category'].value_counts())
print('\n')
print(df['Segment'].value_counts())
print('\n')
print(df['Ship Mode'].value_counts())
print('\n')
print(df['Ship Mode'].value_counts())

Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64


Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64


Sub-Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64


Segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64


Ship Mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64

In [85]:
# We can see all the values in categorical columns are consistance and there is no spelling error or also there is no extra spacing

In [86]:
# Creating New Columns
df['Order_Month']=df['Order Date'].dt.month
df['Ship_Month']=df['Ship Date'].dt.month
df['Order_Month_name']=df['Order Date'].dt.month_name()
df['Ship_Month_name']=df['Ship Date'].dt.month_name()
df['Order_Year']=df['Order Date'].dt.year
df['Ship_Year']=df['Ship Date'].dt.year
df['Order_Day']=df['Order Date'].dt.day
df['Order_Day_name']=df['Order Date'].dt.day_name()
df['Ship_Day']=df['Ship Date'].dt.day
df['Ship_Day_name']=df['Ship Date'].dt.day_name()

In [88]:
df[['Order Date','Ship Date','Order_Month','Order_Month_name','Order_Day_name']].head(10)

  Order Date  Ship Date  Order_Month Order_Month_name Order_Day_name
0 2016-11-08 2016-11-11           11         November        Tuesday
1 2016-11-08 2016-11-11           11         November        Tuesday
2 2016-06-12 2016-06-16            6             June         Sunday
3 2015-10-11 2015-10-18           10          October         Sunday
4 2015-10-11 2015-10-18           10          October         Sunday
5 2014-06-09 2014-06-14            6             June         Monday
6 2014-06-09 2014-06-14            6             June         Monday
7 2014-06-09 2014-06-14            6             June         Monday
8 2014-06-09 2014-06-14            6             June         Monday
9 2014-06-09 2014-06-14            6             June         Monday

In [97]:
df.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit,Order_Month,Ship_Month,Order_Year,Ship_Year,Order_Day,Ship_Day
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355648,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896,7.809686,7.743146,2015.722233,2015.737442,15.468481,15.883730
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000,1.000000,1.000000,2014.000000,2014.000000,1.000000,1.000000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750,5.000000,5.000000,2015.000000,2015.000000,8.000000,8.000000
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500,9.000000,9.000000,2016.000000,2016.000000,15.000000,16.000000
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000,11.000000,11.000000,2017.000000,2017.000000,23.000000,24.000000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000,12.000000,12.000000,2017.000000,2018.000000,31.000000,31.000000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108,3.284654,3.340476,1.123555,1.126141,8.748327,8.802677

In [101]:
# Feature Engineering
df['Sales_level']=df['Sales'].apply(
    lambda x: 'Very High' if x>10000 else 'High' if x>1000 else 'Low'
)
df['Sales_level'].value_counts()

Sales_level
Low          9526
High          463
Very High       5
Name: count, dtype: int64

In [105]:
df['Profit_Status']=df['Profit'].apply(
    lambda x: 'High' if x>1000 else 'Low' if x>0 else 'Loss'
)
df['Profit_Status'].value_counts()

Profit_Status
Low     8016
Loss    1936
High      42
Name: count, dtype: int64

In [109]:
import numpy as nm
df['Quantity_Type']=nm.where(
    df['Quantity']>=10, 'Bulk Order', 'Regular Order'
)
df['Quantity_Type'].value_counts()

Quantity_Type
Regular Order    9824
Bulk Order        170
Name: count, dtype: int64

In [110]:
df.to_csv('Cleaned_SuperStore_Sales.csv', index=False)